[package]
name = "art-generator"
version = "0.1.0"
authors = ["Zeh Fernando <zeh@zehfernando.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.2.10"
